# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/nbarsukov/projects/Diplome2021/YRake/interface/ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(962, 628)
        self.CentralWidget = QtWidgets.QWidget(MainWindow)
        self.CentralWidget.setObjectName("CentralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.CentralWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TextEdit = QtWidgets.QTextEdit(self.CentralWidget)
        self.TextEdit.setObjectName("TextEdit")
        self.gridLayout_2.addWidget(self.TextEdit, 0, 0, 1, 2)
        self.ExtractButton = QtWidgets.QPushButton(self.CentralWidget)
        self.ExtractButton.setObjectName("ExtractButton")
        self.gridLayout_2.addWidget(self.ExtractButton, 5, 0, 1, 2)
        self.MethodsBox = QtWidgets.QGroupBox(self.CentralWidget)
        self.MethodsBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MethodsBox.sizePolicy().hasHeightForWidth())
        self.MethodsBox.setSizePolicy(sizePolicy)
        self.MethodsBox.setMaximumSize(QtCore.QSize(800, 800))
        self.MethodsBox.setObjectName("MethodsBox")
        self.gridLayout = QtWidgets.QGridLayout(self.MethodsBox)
        self.gridLayout.setContentsMargins(9, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.rake_checkbox = QtWidgets.QCheckBox(self.MethodsBox)
        self.rake_checkbox.setObjectName("rake_checkbox")
        self.gridLayout.addWidget(self.rake_checkbox, 2, 0, 1, 1)
        self.textrank_checkbox = QtWidgets.QCheckBox(self.MethodsBox)
        self.textrank_checkbox.setObjectName("textrank_checkbox")
        self.gridLayout.addWidget(self.textrank_checkbox, 4, 0, 1, 1)
        self.yakemodified_checkbox = QtWidgets.QCheckBox(self.MethodsBox)
        self.yakemodified_checkbox.setEnabled(True)
        self.yakemodified_checkbox.setChecked(True)
        self.yakemodified_checkbox.setObjectName("yakemodified_checkbox")
        self.gridLayout.addWidget(self.yakemodified_checkbox, 1, 0, 1, 1)
        self.yake_checkbox = QtWidgets.QCheckBox(self.MethodsBox)
        self.yake_checkbox.setEnabled(True)
        self.yake_checkbox.setChecked(False)
        self.yake_checkbox.setTristate(False)
        self.yake_checkbox.setObjectName("yake_checkbox")
        self.gridLayout.addWidget(self.yake_checkbox, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.MethodsBox, 1, 0, 1, 1)
        self.FileBox = QtWidgets.QGroupBox(self.CentralWidget)
        self.FileBox.setObjectName("FileBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.FileBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_name_label = QtWidgets.QLabel(self.FileBox)
        self.file_name_label.setObjectName("file_name_label")
        self.horizontalLayout.addWidget(self.file_name_label)
        self.select_file_button = QtWidgets.QPushButton(self.FileBox)
        self.select_file_button.setObjectName("select_file_button")
        self.horizontalLayout.addWidget(self.select_file_button)
        self.gridLayout_2.addWidget(self.FileBox, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.CentralWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.CentralWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 962, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.show_settings)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ExtractButton.setText(_translate("MainWindow", "Извлечь"))
        self.MethodsBox.setTitle(_translate("MainWindow", "Методы извлечения ключевых слов"))
        self.rake_checkbox.setText(_translate("MainWindow", "Rake"))
        self.textrank_checkbox.setText(_translate("MainWindow", "Textrank"))
        self.yakemodified_checkbox.setText(_translate("MainWindow", "Yake modified"))
        self.yake_checkbox.setText(_translate("MainWindow", "Yake"))
        self.FileBox.setTitle(_translate("MainWindow", "Выбор файла"))
        self.file_name_label.setText(_translate("MainWindow", "Имя файла"))
        self.select_file_button.setText(_translate("MainWindow", "Выбрать файл"))
        self.pushButton.setText(_translate("MainWindow", "Настройки"))
